### ISSUE TITLE
parameter LogD usage in modl algorithm

### ISSUE THREAD

**Issue by kiminh** [liuzhiqiangruc/dml#10]
ts/modl.c 
double * modl(double v[], int a[], double * LogD, int n, int * nd)

what does the paramter LogD mean? and would you please provide a test case?  It's a little bit different from the case you describe on the blog.
http://liuzhiqiangruc.iteye.com/blog/2145143.

would you please list the related paper?

Thanks a lot.

**Comment by liuzhiqiangruc** [comment]
you can find the test case in source code.
